### ISSUE TITLE
Add support to Eclipse Vert.x JsonObject

### ISSUE THREAD

**Issue by oswaldobapvicjr** [oswaldobapvicjr/jsonmerge#12]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add new `JsonProvider` implementation to Vert.x's JsonObject.

**Describe alternatives you've considered**
N/A

**Additional context**
vert.x is a toolkit for reactive programming created by the developers of Eclipse. It's used by 1K+ open source projects in Maven Central. And it encapsulates a special JsonObject implementation used by that framework.

```xml
<!-- https://mvnrepository.com/artifact/io.vertx/vertx-core -->
<dependency>
    <groupId>io.vertx</groupId>
    <artifactId>vertx-core</artifactId>
    <version>4.3.3</version>
</dependency>
```

This enhancement aims to provide JSON Merge to work seamlessly with the JsonObject handled by the vert.x framework.

The new dependency shall be optional to avoid an unnecessary dependency on applications that do not use vert.x.

**Tasks**
- [x] Add vert.x dependency (optional) to the `jsonmerge-core` project.
- [x] Create a new `JsonProvider` implementation named `VertxJsonProvider` 
- [x] Create JUnit test suite `VertxJsonProviderTest`
- [x] Create JUnit test suite `JsonMergerVertxJsonProvider` extending `JsonMergerTest` to secure that all tests available for the other providers may pass for the new provider as well
- [ ] Update README.md with new provider information

**Comment by oswaldobapvicjr** [comment]
A medium-severity vulnerability is associated with the latest Vert.x version available (4.3.3).
There is currently no published exploit for this vulnerability. So this enhancement must be put "on hold" for a while.

More details of the vulnerability can be found at:
https://security.snyk.io/vuln/SNYK-JAVA-IONETTY-1042268
